src/background.js
src/content.js
src/popup.js

Add support for custom selectors with `{{selector:}}`

Support custom selectors

---

src/popup.js
src/settings.html
src/settings.js
src/style.scss
src/styles/dragging.scss
src/styles/popup.scss
src/styles/settings.scss

Add drag to reorder for templates, vaults, and properties. Make sure these are displayed in the right order in the popup, and json exports.

Drag to reorder

---

src/core/popup.ts
src/popup.html
src/utils/content-extractor.ts
src/utils/obsidian-note-creator.ts

Simplify how we load variables

Refactor variables

---

README.md
src/content.ts
src/core/popup.ts
src/utils/content-extractor.ts

Add support for schema.org and `list` filter

Schema variables

---

src/managers/template-manager.ts
src/styles/dragging.scss
src/styles/settings.scss

Avoid conflicting with text selection in inputs

Improve dragging properties

---

src/core/popup.ts
src/icons/icons.ts
src/popup.html
src/styles/buttons.scss
src/styles/popup.scss
src/utils/storage-utils.ts

- Expandable textarea for the file name
- Automatically remove illegal file name characters
- Expandable properties section
- Reduce the number of borders making the popup feel lighter and more focused

Improve popup UI

---

src/core/popup.ts
src/core/settings.ts
src/managers/general-settings-ui.ts
src/managers/general-settings.ts
src/managers/template-manager.ts
src/managers/template-ui.ts
src/settings.html
src/utils/auto-save.ts
src/utils/drag-and-drop.ts
src/utils/import-export.ts
src/utils/routing.ts
src/utils/storage-utils.ts
src/utils/string-utils.ts
src/utils/ui-utils.ts

Split up code and improve how extension is initially started, create default template

Initialize extension

---

README.md
src/content.ts
src/core/popup.ts
src/utils/content-extractor.ts
src/utils/filters.ts
src/utils/markdown-converter.ts

- Add `fullHtml` variable
- Add `markdown` filter

Markdown filter

---

src/utils/markdown-converter.ts

- Better support for nested equations in tables
- Better support for equations in figures
- Remove unnecessary edit/anchor links

Better support for math, arXiv, Wikipedia, GitHub

---

README.md
src/utils/content-extractor.ts
src/utils/date-utils.ts
src/utils/filters.ts
src/utils/markdown-converter.ts
src/utils/string-utils.ts

- Simplify selection/extraction → Readability
- Fix a few `math` element issues

Order of operations

---

README.md
src/styles/inspect-variables.scss
src/utils/content-extractor.ts
src/utils/string-utils.ts
src/utils/triggers.ts

Improve support for multiple schema on one page.

Multiple schema

---

README.md
src/utils/debug.ts
src/utils/filters.ts
src/utils/filters/map.ts
src/utils/filters/template.ts

- Update syntax to better deal with objects
- Don't process filters within map

Map and template improvements

---

README.md
src/types/filters.ts
src/types/types.ts
src/utils/content-extractor.ts
src/utils/filters.ts
src/utils/filters/kebab.ts
src/utils/filters/markdown.ts
src/utils/filters/strip_attr.ts
src/utils/filters/strip_md.ts
src/utils/filters/strip_tags.ts

- Add `strip_tags`
- Add `strip_attr`
- Rename `strip_md` for consistency

Strip filters

---

src/utils/debug.ts
src/utils/markdown-converter.ts

Gracefully skip Turndown GFM

---

README.md
src/utils/filters.ts
src/utils/filters/replace.ts

Better support for escaping in replace filter

Replace fixes

---

src/managers/template-ui.ts

Fixes a bug that the *Note location* of templates was not saved.

Update template path from form

---

src/core/popup.ts
src/core/settings.ts
src/managers/general-settings.ts
src/managers/property-types-manager.ts
src/managers/settings-section-ui.ts
src/managers/template-manager.ts
src/managers/template-ui.ts
src/settings.html
src/style.scss
src/styles/buttons.scss
src/styles/settings.scss
src/styles/templates.scss
src/styles/tree-items.scss
src/types/types.ts
src/utils/import-export.ts
src/utils/memoize.ts
src/utils/obsidian-note-creator.ts
src/utils/storage-utils.ts
src/utils/triggers.ts
xcode/Obsidian Web Clipper/Obsidian Web Clipper.xcodeproj/xcuserdata/kepano.xcuserdatad/xcschemes/xcschememanagement.plist

- New Properties view in settings that shows a list of all properties in use
- Ability to import and export types.json in the same format as Obsidian
- Autocomplete property names in the template form
- Default values for properties
- Memoization to speed template loading

Global property types

---

docs/Capture web pages.md
docs/Filters.md
docs/Highlight web pages.md
docs/Introduction to Obsidian Web Clipper.md
docs/Templates.md
docs/Troubleshoot Web Clipper.md
docs/Variables.md
src/content.ts
src/utils/variables/schema.ts

Support for `@graph` in schema data. Closes #127

Graph schema

---

src/utils/markdown-converter.ts

fix: check the `display` property of `<math>` elements

---

src/locales/pt-BR/messages.json

add brazilian portuguese translation

---

src/locales/id/messages.json

Added/revised Indonesian translation

Indonesian Translation

---

src/core/popup.ts
src/utils/storage-utils.ts

Initial history list. Basis for personal clipping stats, and open future options for dealing with URLs that have been clipped before, see #112
In the future if the URL is recognized, we can attempt to open existing note based on the previous path, or add content to existing note

Basic history list

---

src/locales/zh-TW/messages.json

Added/revised Traditional Chinese translations

add Traditional Chinese translations

---

docs/Filters.md
src/utils/filters.ts
src/utils/filters/replace.ts
src/utils/parser-utils.ts

Add regex support for replace filter. Closes #182

Regex replace

---

src/utils/content-extractor.ts
src/utils/extractor-registry.ts
src/utils/extractors/_base.ts
src/utils/extractors/reddit.ts
src/utils/extractors/twitter.ts

Since Readability has poor results with certain sites, this is an alternative way to fill the `{{content}}` variable with more useful content.

Extractors

---

package-lock.json
src/locales/bn/messages.json
src/utils/i18n.ts

Obsidian web clipper Bengali translation

---

src/locales/fr/messages.json

Update French localization for clarity and consistency

Update French locales

---

src/reader.scss
src/types/types.ts
src/utils/extractors/_conversation.ts
src/utils/extractors/chatgpt.ts
src/utils/extractors/claude.ts
src/utils/reader.ts

Streamline conversation extractors so we can add more

Conversation

---

src/content.ts
src/highlighter.scss
src/utils/highlighter-overlays.ts
src/utils/highlighter.ts
src/utils/reader.ts

Revamp highlighter mode:
- Uses a method similar to text fragment URLs that doesn't rely on xpaths — more robust to DOM changes
- Remove element highlighting and improve text highlighting UX
- Add ability to copy link to highlighted page

Revamp highlighter using text fragment approach

---

.gitignore
src/utils/content-extractor.ts
src/utils/highlighter-overlays.ts
src/utils/highlighter.ts

Revert back to old highlighter, with a few improvements to avoid highlighting entire page

Revert highlighter
